### ISSUE TITLE
`DynamicCore` doesn't handle named only arguments properly

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/PythonLibCore#111]
For example, `arg` in this example isn't handled properly:

```python
class Example(DynamicCore):
    def __init__(self):
        super().__init__([])

    @keyword
    def kw(self, *, arg):
        print(arg)
```

Libdoc reports `arg` as a normal argument, not as named-only as it should. Luckily execution like
```
Kw    arg=value
```
works as expected so named-only arguments aren't totally broken. Invalid usage like
```
Kw    value
```
isn't handled properly, though.

**Comment by pekkaklarck** [comment]
This was initially submitted to Robot's tracker as https://github.com/robotframework/robotframework/issues/4644.

**Comment by aaltat** [comment]
So do I get it correctly that in the above case, PLC should return `['*', 'named']`?

**Comment by aaltat** [comment]
Add #117 tests
