### ISSUE TITLE
robotlibcore.py placed right into root of site-packages/ 

### ISSUE THREAD

**Issue by rasjani** [robotframework/PythonLibCore#149]
Would be a bit more cleaner if placed into it's own subdirectory inside site-packages. While the file is probably never going to clash with anything - just for hygiene's sake ?

**Comment by aaltat** [comment]
I have tough the same thing, because the single file is getting pretty big and would benefit from splitting smaller pieces. But it didn’t bother me enough that I would have done something about it. Do you want to give it a go?

**Comment by rasjani** [comment]
Currently i do have some wip that moves the `src/robotlibcore.py` into `src/robotlibcore/__init__.py`  and changes to setup.py to build the sdist/wheels so that nothing is placed into root.. all utests and atests do pass with this setup.

1. i dont like to have everything on `__init__.py`
2. I don't have any major feelings on how to do the split.
3. If code is split up, can i rely on atests that all the stuff that should be exported from `__init__.py` will get exported and not get regressions ? This also has the downside of having to manually give the dunder init up to date if/when there's changes what should and should get exposed  ..


But in general, if you have any guidelines on what you would like to split, i can take a stab. However, I'd prefer to only do the shuffling part and not change any inheritance like mentioned in issue #1

**Comment by aaltat** [comment]
1. Agree, it moves the problem to new file.
2. I never gave it much thinking how do to the split. Perhaps by splitting hybrid core methods in one place and dynamic core stuff in other file. And perhaps keyword builder also in separate file.
3. I think you can do something with __all__ https://docs.python.org/3/tutorial/modules.html#importing-from-a-package

**Comment by aaltat** [comment]
And doing only the shuffling part is also good way to go.

**Comment by rasjani** [comment]
https://github.com/robotframework/PythonLibCore/pull/150 -- first pick .. Just point out what you what you what changed.
