### ISSUE TITLE
Add support for get_keyword_source API method for Robot Framework 3.2

### ISSUE THREAD

**Issue by aaltat** [robotframework/PythonLibCore#26]
Robot Framework 3.2 will enhance the dynamic library API and add to`get_keyword_source` API call. See more details in https://github.com/robotframework/robotframework/issues/3507 and  https://github.com/robotframework/robotframework/issues/3516 Add support to PythonLibCore for the new API.

**Comment by pekkaklarck** [comment]
This functionality had problems with decorators on Robot side that should probably be fixed here as well. See my comment here for more details:
https://github.com/robotframework/robotframework/issues/3516#issuecomment-605682914

**Comment by aaltat** [comment]
Because of this and forgetting the lambda I am thinking to change the functionality towards what the python returns. But definitely needs fixing.

**Comment by pekkaklarck** [comment]
Taking lambdas etc. into account isn't too hard:
https://github.com/robotframework/robotframework/blob/master/src/robot/running/handlers.py#L164

**Comment by aaltat** [comment]
Fixed in #33
