### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/PythonLibCore#4]
Needs setup.py etc. Package should also be uploaded to PyPI.

**Comment by yo-ga** [comment]
@pekkaklarck If this enhancement is still needed, I'd like to pick and try it.

**Comment by pekkaklarck** [comment]
Yes it is! This whole project has been neglected lately due to me being busy with RF 3.2. All kind of help moving the project forward is appreciated.

We've used our own [rellu](https://github.com/robotframework/rellu) tool to ease making releases and it's to some extend already used here as well. Actual packaging has been just standard Python stuff.
