### ISSUE TITLE
Installing PythonLibCore

### ISSUE THREAD

**Issue by youarelev** [robotframework/PythonLibCore#6]
Do we have this tool in pip repo?

How to use it in my sources?

My next task: overwrite Selenium2Libraries keyword "Open Browser" - add some logic and call your original "Open Browser" with another arguments
Example: I want change default Firefox browser to Chrome

Can I do it using this tool?

**Comment by pekkaklarck** [comment]
SeleniumLibrary includes this code so you don't need to install it. How to extend SL is a topic that belongs to its forums.
