### ISSUE TITLE
robotframework-robotlibcore or robotframework-pythonlibcore

### ISSUE THREAD

**Issue by RomaCZ** [robotframework/PythonLibCore#69]
Hi,
is it robot or python libcore?
Install instructions here on github says pip install robotframework-robotlibcore
but on pypy.org there is only pip install robotframework-pythonlibcore

**Comment by aaltat** [comment]
It is PythonLibCore, in [pypi](https://pypi.org/project/robotframework-pythonlibcore/). What installation instructions are referring to?

**Comment by RomaCZ** [comment]
Here: https://github.com/robotframework/PythonLibCore/blob/master/docs/PythonLibCore-2.1.0.rst
_If you have pip installed, just run

pip install --upgrade robotframework-robotlibcore

to install the latest available release or use

pip install robotframework-robotlibcore==2.1.0_

**Comment by aaltat** [comment]
Ah, that is bug. Thank you for the report.
