### ISSUE TITLE
${None} type conversion does not work correctly 

### ISSUE THREAD

**Issue by aaltat** [robotframework/PythonLibCore#81]
If keyword argument has type hint `Optional[str] = None` then PLC has a bug that type information is passed incorrectly to RF side and ${None} is converted to string. More details in https://github.com/robotframework/SeleniumLibrary/issues/1733

**Comment by pekkaklarck** [comment]
Did you already check _can_ this be fixed on PLC side without changes to the dynamic API? If not, we need to add an issue about that to RF 4.1 scope as well.

**Comment by aaltat** [comment]
I was about to start taking a look, but I was wondering that how the type information should be provided?

**Comment by aaltat** [comment]
Now I remember, we do by purpose because of RF 3, in [here](https://github.com/robotframework/PythonLibCore/blob/master/src/robotlibcore.py#L273-L292). I guess we should not that anymore with RF 4.

**Comment by pekkaklarck** [comment]
Great work! 👍
