### ISSUE TITLE
Support keyword-only arguments

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/PythonLibCore#9]
RF 3.1 got support for keyword-only arguments (robotframework/robotframework#2555) and also the dynamic API supports them (robotframework/robotframework#2897). PythonLibCore should support them as well.

**Comment by aaltat** [comment]
There is something that I do not see but for me it looks like kwargs are supported. I added tests in #32 and all works. Should this be closed?

**Comment by pekkaklarck** [comment]
This isn't about keyword arguments only, this is about [keyword-only arguments](https://www.python.org/dev/peps/pep-3102/). :smile: 

`**kwargs` works just fine with Python 2 and with RF 2.9+. I would expect there to be tests for it with PythonLibCore as well but I may be wrong.

**Comment by aaltat** [comment]
Ah that we support `def method (*varargs, something=False)` in PythonLibCore. Yes that is not supported.

**Comment by aaltat** [comment]
So how should the `get_keyword_arguments`return if keyword method looks like: `def method (*varargs, something=False)`? Something like this with RF 3.2 syntax: `["*varargs", ("something", bool)]`

**Comment by pekkaklarck** [comment]
That looks right to me. But to be honest, I think I forgot to tests this default syntax with kwonly args. I expect/hope the code to work but need to add those tests anyway. Hopefully you can also add some acceptance tests to PyLibCo that test this end-to-end.

**Comment by aaltat** [comment]
And if I have this: 
```
def foo(self, *varargs, other)
    pass
```
I should return `["*varargs", "other"]`. Need to think how handle all this.

**Comment by pekkaklarck** [comment]
Yes, kwonly args without default values need to be handled like that. As I recommended elsewhere, it probably would be a good idea to have an ArgumentSpec objcet that contains all this information and can then turned to a list of arguments. Assuming the spec object had same attributes as [similar object on Robot side](https://github.com/robotframework/robotframework/blob/master/src/robot/running/arguments/argumentspec.py#L26), something like this could work:

```python
def __iter__(self):
    for arg in self.positional:
        yield self._arg_with_possible_default(arg)
    if self.varargs:
        yield '*' + self.varargs
    for arg in self.kwonly:
        yield self._arg_with_possible_default(arg)
    if self.kwargs:
        yield '**' + self.kwargs

def _arg_with_possible_default(self, arg):
    if arg not in self.defaults:
        return arg
    arg_and_default = (arg, self.defaults[arg])
    if RF31:
        return '%s=%s' % arg_and_default
    return arg_and_default
```

**Comment by aaltat** [comment]
What, `def bar(*, other):` is valid syntax. Did not know that one -> more tests required. Any other strange things that would be good to know?

**Comment by pekkaklarck** [comment]
Yeah, you can use `*` when you want kwonlyargs but don't have varargs. Don't remember there being anything else special.
