### ISSUE TITLE
Decorator resolves as wron file path 

### ISSUE THREAD

**Issue by aaltat** [robotframework/PythonLibCore#99]
Reported in https://github.com/MarketSquare/robotframework-browser/issues/2382

Original issue says 
Describe the bug

In the documentation generated with libdoc (in JSON or libspec format), the source file for the keyword New Context is Browser/utils/deprecated.py.

To Reproduce

Execute libdoc Browser browser.json
Search for "name": "New Context" and then for "source":
Expected behavior

The source of the keyword New Context is 

OS: Windows 10

The keyword New Context has the following definition
```python
@keyword(tags=("Setter", "BrowserControl"))
@attribute_warning(
    old_args=("videosPath", "videoSize"), new_args=("recordVideo", "recordVideo")
)
def new_context(
    self,
    ...
)
```
Apparently, libdoc expects that the line after the keyword decorator is a function definition.

**Comment by d-biehl** [comment]
https://github.com/robotframework/PythonLibCore/blob/ef35336fbc895d3d329a6d61be52501c2a5a54d4/src/robotlibcore.py#L142 

should be:

```
return os.path.normpath(inspect.getsourcefile(inspect.unwrap(method)))
```
it is the same like robotframework gets the source for a keyword.

**Comment by d-biehl** [comment]
sorry for my late answer ;-)

yes I can provide a PR, but only at the end of the week, if it's ok for you. Just have a few days vacation ;-)

**Comment by aaltat** [comment]
No rush take your time.
